name: Build GravitRDR

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: macos-13

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python for node-gyp
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Setup Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install npm dependencies
        run: |
          npm install --legacy-peer-deps

      - name: Install grunt-cli globally
        run: |
          npm install -g grunt-cli@1.4.3

      - name: Run Grunt build
        run: npx grunt build
      
      - name: Upload macOS artifact
        uses: actions/upload-artifact@v4
        with:
          name: gravitRDR-osx
          path: build/system-binaries/GravitRDR/osx

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: gravitRDR-win
          path: build/system-binaries/GravitRDR/win

      - name: Upload Linux artifact
        uses: actions/upload-artifact@v4
        with:
          name: gravitRDR-linux
          path: build/system-binaries/GravitRDR/linux

      