name: Build GravitRDR

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true  # Cancels all older/queued runs

jobs:
  build:
    runs-on: macos-latest  # macOS 14 for runner availability

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: true  # Allow committing package-lock.json

      - name: Check runner status
        run: |
          echo "Checking runner status..."
          sysctl -n machdep.cpu.brand_string
          sw_vers
          xcodebuild -version
          echo "Checking Homebrew prefix..."
          echo $HOMEBREW_PREFIX
          arch
        # Diagnostic to confirm macOS, architecture, and Homebrew setup

      - name: Setup x86_64 Homebrew
        run: |
          arch -x86_64 /bin/bash -c '
            # Install Homebrew in /usr/local for x86_64
            /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
            echo "export PATH=/usr/local/bin:/usr/local/sbin:$PATH" >> ~/.zshrc
            source ~/.zshrc
            brew --version
          '

      - name: Install Homebrew dependencies
        run: |
          arch -x86_64 /bin/bash -c '
            export PATH=/usr/local/bin:/usr/local/sbin:$PATH
            brew update
            brew install nasm
            brew install libtool
            brew install gettext
            brew install openssl@3
            brew link gettext --force
            brew link openssl@3 --force
            nasm --version
            glibtool --version
            ls -l /usr/local/lib/libssl* /usr/local/lib/libcrypto* /usr/local/lib/libintl*
            brew list gettext
            brew list openssl@3
          '
        # Installs nasm, libtool, gettext, openssl@3 in /usr/local for Rosetta

      - name: Setup Python 3.7 for node-gyp
        env:
          LDFLAGS: "-L/usr/local/lib"
          CFLAGS: "-I/usr/local/include"
        run: |
          arch -x86_64 /bin/bash -c '
            export PATH=/usr/local/bin:/usr/local/sbin:$PATH
            /usr/local/bin/python3.7 -c "import ssl; print(ssl.OPENSSL_VERSION)"
          '
        # Verifies SSL module before actions/setup-python
        continue-on-error: true  # Allow continuation if pre-check fails
      - uses: actions/setup-python@v5
        with:
          python-version: '3.7'
          architecture: 'x64'

      - name: Setup Node 10.x and npm 6 using nvm (Rosetta x86_64)
        run: |
          arch -x86_64 /bin/bash -c '
            export PATH=/usr/local/bin:/usr/local/sbin:$PATH
            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
            export NVM_DIR="$HOME/.nvm"
            source "$NVM_DIR/nvm.sh"
            nvm install 10
            nvm use 10
            npm install -g npm@6
            echo "node version: $(node -v)"
            echo "npm version: $(npm -v)"
            echo "python version: $(python3 --version)"
          '

      - name: Install npm dependencies
        run: |
          arch -x86_64 /bin/bash -c '
            export PATH=/usr/local/bin:/usr/local/sbin:$PATH
            export NVM_DIR="$HOME/.nvm"
            source "$NVM_DIR/nvm.sh"
            nvm use 10
            npm install --legacy-peer-deps
            npm ci || npm install --legacy-peer-deps
            git add package-lock.json
            git config user.name "GitHub Actions"
            git config user.email "actions@github.com"
            git commit -m "Update package-lock.json" || echo "No changes to commit"
          '

      - name: Install Bower globally
        run: |
          arch -x86_64 /bin/bash -c '
            export PATH=/usr/local/bin:/usr/local/sbin:$PATH
            export NVM_DIR="$HOME/.nvm"
            source "$NVM_DIR/nvm.sh"
            nvm use 10
            npm install -g bower
          '

      - name: Install Bower dependencies
        run: |
          arch -x86_64 /bin/bash -c '
            export PATH=/usr/local/bin:/usr/local/sbin:$PATH
            export NVM_DIR="$HOME/.nvm"
            source "$NVM_DIR/nvm.sh"
            nvm use 10
            bower install --allow-root
          '

      - name: Run Grunt
        run: |
          arch -x86_64 /bin/bash -c '
            export PATH=/usr/local/bin:/usr/local/sbin:$PATH
            export NVM_DIR="$HOME/.nvm"
            source "$NVM_DIR/nvm.sh"
            nvm use 10
            ./node_modules/.bin/grunt
          '