name: NodeJS with Grunt (Legacy)

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: macos-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Downgrade npm to 4.6.1 (last stable pre-lock)
      run: npm install -g npm@4.6.1

    - name: Show Node and npm versions
      run: |
        node --version
        npm --version

    - name: Clean potential modern lockfiles
      run: rm -f package-lock.json

    - name: Install npm dependencies
      run: npm install

    - name: Install Bower globally
      run: npm install -g bower

    - name: Install bower dependencies
      run: bower install --allow-root

    - name: Run Grunt
      run: grunt
