name: Build GravitRDR

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true  # Cancels all older/queued runs

jobs:
  build:
    runs-on: macos-latest  # macOS 14 for runner availability

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: true  # Allow committing package-lock.json

      - name: Check runner status
        run: |
          echo "Checking runner status..."
          sysctl -n machdep.cpu.brand_string
          sw_vers
          xcodebuild -version
          brew --version
        # Diagnostic to confirm macOS version and Homebrew

      - name: Install Homebrew dependencies
        run: |
          arch -x86_64 /bin/bash -c '
            brew update
            brew install nasm
            brew install libtool
            brew install gettext
            nasm --version
            glibtool --version
            brew list gettext
          '
        # Installs nasm, libtool, and gettext for libintl.8.dylib

      - name: Setup Python 3.7 for node-gyp
        uses: actions/setup-python@v5
        with:
          python-version: '3.7'
          architecture: 'x64'

      - name: Setup Node 10.x and npm 6 using nvm (Rosetta x86_64)
        run: |
          arch -x86_64 /bin/bash -c '
            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
            export NVM_DIR="$HOME/.nvm"
            source "$NVM_DIR/nvm.sh"
            nvm install 10
            nvm use 10
            npm install -g npm@6
            echo "node version: $(node -v)"
            echo "npm version: $(npm -v)"
            echo "python version: $(python3 --version)"
          '

      - name: Install npm dependencies
        run: |
          arch -x86_64 /bin/bash -c '
            export NVM_DIR="$HOME/.nvm"
            source "$NVM_DIR/nvm.sh"
            nvm use 10
            npm install --legacy-peer-deps
            npm ci || npm install --legacy-peer-deps
            git add package-lock.json
            git config user.name "GitHub Actions"
            git config user.email "actions@github.com"
            git commit -m "Update package-lock.json" || echo "No changes to commit"
          '

      - name: Install Bower globally
        run: |
          arch -x86_64 /bin/bash -c '
            export NVM_DIR="$HOME/.nvm"
            source "$NVM_DIR/nvm.sh"
            nvm use 10
            npm install -g bower
          '

      - name: Install Bower dependencies
        run: |
          arch -x86_64 /bin/bash -c '
            export NVM_DIR="$HOME/.nvm"
            source "$NVM_DIR/nvm.sh"
            nvm use 10
            bower install --allow-root
          '

      - name: Run Grunt
        run: |
          arch -x86_64 /bin/bash -c '
            export NVM_DIR="$HOME/.nvm"
            source "$NVM_DIR/nvm.sh"
            nvm use 10
            ./node_modules/.bin/grunt
          '