name: NodeJS with Grunt

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: macos-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Show Node and npm versions
      run: |
        node --version
        npm --version

    - name: Install npm dependencies (with legacy peer deps)
      run: npm install --legacy-peer-deps

    - name: Install Bower globally
      run: npm install -g bower

    - name: Install bower dependencies
      run: bower install --allow-root

    - name: Run Grunt
      run: grunt
