name: Build GravitRDR

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: macos-13  # must be macos-13 to support x86_64 Rosetta

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node 0.10.48 and npm 1.4.28 using nvm (Rosetta x86_64)
      run: |
        arch -x86_64 /bin/bash -c '
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
          export NVM_DIR="$HOME/.nvm"
          source "$NVM_DIR/nvm.sh"
          nvm install 0.10.48
          nvm use 0.10.48
          npm install -g npm@1.4.28
          npm config set python /usr/bin/python
          echo "node version: $(node -v)"
          echo "npm version: $(npm -v)"
          npm config get python
        '

    - name: Install npm dependencies (legacy peer deps)
      run: |
        arch -x86_64 /bin/bash -c '
          export NVM_DIR="$HOME/.nvm"
          source "$NVM_DIR/nvm.sh"
          nvm use 0.10.48
          npm install --legacy-peer-deps
        '

    - name: Install Bower globally
      run: |
        arch -x86_64 /bin/bash -c '
          export NVM_DIR="$HOME/.nvm"
          source "$NVM_DIR/nvm.sh"
          nvm use 0.10.48
          npm install -g bower
        '

    - name: Install Bower dependencies
      run: |
        arch -x86_64 /bin/bash -c '
          export NVM_DIR="$HOME/.nvm"
          source "$NVM_DIR/nvm.sh"
          nvm use 0.10.48
          bower install --allow-root
        '

    - name: Run Grunt
      run: |
        arch -x86_64 /bin/bash -c '
          export NVM_DIR="$HOME/.nvm"
          source "$NVM_DIR/nvm.sh"
          nvm use 0.10.48
          ./node_modules/.bin/grunt
        '
